# Generated by Django 3.1.3 on 2021-03-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricewash',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Time'),
        ),
    ]
