# Generated by Django 3.1.3 on 2021-03-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20210304_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricewash',
            name='created',
        ),
        migrations.AddField(
            model_name='pricewash',
            name='Data',
            field=models.DateField(auto_now=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='pricewash',
            name='Time',
            field=models.TimeField(auto_now=True, verbose_name='Time'),
        ),
    ]
