# Generated by Django 3.1.3 on 2021-03-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Model cars')),
                ('color', models.CharField(max_length=100, verbose_name='Color cars')),
                ('number', models.CharField(max_length=100, verbose_name='Number cars')),
                ('car_type', models.CharField(choices=[('T', 'Trucks'), ('MSM', 'Medium size machines'), ('C', 'Cars')], default='C', max_length=100, verbose_name='Type cars')),
                ('wash_type', models.CharField(choices=[('TW', 'Thorough washing'), ('WWST', 'Washing with a special tool'), ('ON', 'Only Karcher'), ('EW', 'Engine wash'), ('DTH', 'Darken the balloon')], default='TW', max_length=100, verbose_name='Enter wash type')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name Worker')),
                ('car_type', models.CharField(max_length=100, verbose_name='Car type')),
                ('wash_type', models.CharField(max_length=100, verbose_name='Type wash')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
    ]
