# Generated by Django 3.1.3 on 2021-03-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceWash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('D', '--------'), ('T', 'Trucks'), ('MSM', 'Medium size machines'), ('C', 'Cars')], default='C', max_length=100, verbose_name='Type cars')),
                ('wash_type', models.CharField(choices=[('D', '--------'), ('TW', 'Thorough washing'), ('WWST', 'Washing with a special tool'), ('ON', 'Only Karcher'), ('EW', 'Engine wash'), ('DTH', 'Darken the balloon')], default='TW', max_length=100, verbose_name='Enter wash type')),
                ('price', models.FloatField(default=0)),
            ],
        ),
    ]
