# Generated by Django 3.1.3 on 2021-03-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20210304_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricewash',
            name='Data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='pricewash',
            name='Time',
            field=models.TimeField(verbose_name='Time'),
        ),
    ]
