# Generated by Django 3.1.3 on 2021-03-24 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name Worker')),
                ('started_work', models.DateField(auto_now_add=True)),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('status', models.CharField(choices=[('B', 'Busy'), ('OOW', 'Out-of-work')], default='OOW', max_length=100, verbose_name='Status worker')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('car_type', models.CharField(choices=[('D', '--------'), ('T', 'Trucks'), ('MSM', 'Medium size machines'), ('C', 'Cars')], default='D', max_length=100, verbose_name='Type cars')),
                ('wash_type', models.CharField(choices=[('D', '--------'), ('TW', 'Thorough washing'), ('WWST', 'Washing with a special tool'), ('ON', 'Only Karcher'), ('EW', 'Engine wash'), ('DTH', 'Darken the balloon')], default='D', max_length=100, verbose_name='Enter wash type')),
                ('model', models.CharField(max_length=100, verbose_name='Model cars')),
                ('number', models.CharField(max_length=100, verbose_name='Number cars')),
                ('price', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.worker')),
            ],
        ),
    ]
