# Generated by Django 3.1.3 on 2021-03-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.CharField(choices=[('B', 'Busy'), ('OOW', 'Out-of-work')], default='OOW', max_length=100, verbose_name='Status worker'),
        ),
    ]
